# http web configuration
http:
  port: 8888
  log_level: "info"
  allowed_hosts:
    - "http://shanghanlun.com:7777"
    - "http://117.72.***.38:7777"
    - "http://localhost:5173"
    - "http://localhost:7788"
# GRPC configuration
grpc:
  name: "hu_server_grpc" # changed if necessary
  port: 50001
  log_level: "info"
# database configuration
database:
  url: "postgres://postgres:yx******@117.72.***.38:5432/micro-server-demo?options=-c%20timezone=Asia/Shanghai"
  min_connections: 3 # 最小连接数
  max_connections: 10 # 最大连接数
  connect_timeout_secs: 10
  acquire_timeout_secs: 6
  idle_timeout_secs: 600 # 10分钟
  max_lifetime_secs: 1800 # 30分钟
  sqlx_logging: false
  schema: "public"
  timezone: "Asia/Shanghai"
# redis configuration
redis:
  url: "redis://:yx******@medicine_redis"
  max_open: 20 # 最大连接数
  max_idle: 10 # 最大空闲数
  timeout_sec: 5 # 超时 5 秒
# is development environment
is_dev: false
